name: Go

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v -o myapp ./cmd/relay

    - name: Check if tag is pushed
      id: check_tag
      run: |
        if [ "${{ github.ref_type }}" = "tag" ]; then
          echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
        fi

    - name: Create Release
      if: env.TAG_NAME != ''
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      if: env.TAG_NAME != ''
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./myapp
        asset_name: myapp
        asset_content_type: application/octet-stream
